import { describe, it, expect, vi } from "vitest";
import { deterministicQuote } from "./getQuote.js";

// Fixtures match the wire format stored in businesses.pricing_json_v2 per
// PricingRangeSchema: {service, min, max, unit?, currency?}.
const pricing = {
  ranges: [
    { service: "lawn mowing", min: 40, max: 40, currency: "USD" },
    { service: "lawn mowing", min: 60, max: 90, currency: "USD", params: { size: "large" } },
    { service: "hedge trimming", min: 30, max: 75, currency: "USD" },
    // Also cover the production-seed case where the range has no `currency`
    // field (the schema doesn't require it); the tool defaults to USD.
    { service: "drain cleaning", min: 150, max: 250 },
  ],
};

describe("deterministicQuote", () => {
  it("returns exact when low === high on matched service", () => {
    const q = deterministicQuote({ service: "lawn mowing", params: {} }, pricing);
    expect(q).toEqual({ low: 40, high: 40, currency: "USD", confidence: "exact", basis: "pricing_json_v2" });
  });
  it("returns range when low < high", () => {
    const q = deterministicQuote({ service: "hedge trimming", params: {} }, pricing);
    expect(q).toEqual({ low: 30, high: 75, currency: "USD", confidence: "range", basis: "pricing_json_v2" });
  });
  it("respects param narrowing when the range declares params", () => {
    const q = deterministicQuote({ service: "lawn mowing", params: { size: "large" } }, pricing);
    expect(q).toEqual({ low: 60, high: 90, currency: "USD", confidence: "range", basis: "pricing_json_v2" });
  });
  it("is case/whitespace insensitive on service name", () => {
    const q = deterministicQuote({ service: "  LAWN MOWING  ", params: {} }, pricing);
    expect(q?.low).toBe(40);
  });
  it("returns null on service miss", () => {
    const q = deterministicQuote({ service: "window washing", params: {} }, pricing);
    expect(q).toBeNull();
  });
  it("returns null on param mismatch", () => {
    // Caller supplied a param; the size-free row requires empty params, size-large row requires large.
    const q = deterministicQuote({ service: "lawn mowing", params: { size: "small" } }, pricing);
    expect(q).toBeNull();
  });
  it("defaults currency to USD when the range omits it (wire-format compat)", () => {
    const q = deterministicQuote({ service: "drain cleaning", params: {} }, pricing);
    expect(q).toEqual({
      low: 150,
      high: 250,
      currency: "USD",
      confidence: "range",
      basis: "pricing_json_v2",
    });
  });
});

describe("llmQuoteFallback", () => {
  it("parses a well-formed Claude JSON response into a Quote", async () => {
    vi.doMock("../../lib/anthropic.js", () => ({
      callClaude: vi.fn().mockResolvedValue(JSON.stringify({ low: 50, high: 100, currency: "USD" })),
    }));
    vi.resetModules();
    const { llmQuoteFallback } = await import("./getQuote.js");
    const q = await llmQuoteFallback({
      service: "window cleaning",
      params: {},
      businessName: "Acme",
      businessDescription: "services business",
      pricingRawJson: null,
    });
    expect(q).toEqual({
      low: 50, high: 100, currency: "USD",
      confidence: "estimate",
      basis: "llm_estimate",
      disclaimer: "Estimate generated by AI from public business profile. Confirm with provider before relying.",
    });
  });
  it("returns null when callClaude returns null", async () => {
    vi.doMock("../../lib/anthropic.js", () => ({ callClaude: vi.fn().mockResolvedValue(null) }));
    vi.resetModules();
    const { llmQuoteFallback } = await import("./getQuote.js");
    const q = await llmQuoteFallback({
      service: "x", params: {}, businessName: "A", businessDescription: null, pricingRawJson: null,
    });
    expect(q).toBeNull();
  });
  it("returns null on unparseable response", async () => {
    vi.doMock("../../lib/anthropic.js", () => ({ callClaude: vi.fn().mockResolvedValue("not json") }));
    vi.resetModules();
    const { llmQuoteFallback } = await import("./getQuote.js");
    const q = await llmQuoteFallback({
      service: "x", params: {}, businessName: "A", businessDescription: null, pricingRawJson: null,
    });
    expect(q).toBeNull();
  });
});
