import { z } from "zod";
import type { Request } from "express";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { getDb } from "../../db.js";
import { getQuoteInput } from "../../manifest/tools.js";
import { callClaude } from "../../lib/anthropic.js";
import { withAgentRequestLog } from "../../lib/agentRequestLogger.js";

export interface PricingRange {
  service: string;
  low: number;
  high: number;
  currency: string;
  params?: Record<string, string>;
}
export interface PricingJson { ranges: PricingRange[] }

export interface Quote {
  low: number;
  high: number;
  currency: string;
  confidence: "exact" | "range" | "estimate";
  basis: "pricing_json_v2" | "llm_estimate";
  disclaimer?: string;
}

const norm = (s: string) => s.trim().toLowerCase();

function paramsMatch(required: Record<string, string> | undefined, given: Record<string, string>): boolean {
  if (!required) return Object.keys(given).length === 0;
  for (const [k, v] of Object.entries(required)) {
    if (given[k] !== v) return false;
  }
  return true;
}

/**
 * Deterministic quote. Returns null on miss; Task 6 wraps this with the LLM fallback.
 * Confidence: "exact" when low === high, "range" otherwise. Never returns "estimate".
 */
export function deterministicQuote(
  args: { service: string; params: Record<string, string> },
  pricing: PricingJson
): Quote | null {
  const target = norm(args.service);
  for (const r of pricing.ranges) {
    if (norm(r.service) !== target) continue;
    if (!paramsMatch(r.params, args.params)) continue;
    return {
      low: r.low,
      high: r.high,
      currency: r.currency,
      confidence: r.low === r.high ? "exact" : "range",
      basis: "pricing_json_v2",
    };
  }
  return null;
}

const LLM_DISCLAIMER =
  "Estimate generated by AI from public business profile. Confirm with provider before relying.";

export async function llmQuoteFallback(opts: {
  service: string;
  params: Record<string, string>;
  businessName: string;
  businessDescription: string | null;
  pricingRawJson: string | null;
}): Promise<Quote | null> {
  const system =
    "You estimate prices for small businesses based on the business profile the user provides. " +
    "You respond ONLY with a JSON object of shape {\"low\": number, \"high\": number, \"currency\": string}. " +
    "No other fields. No prose. If you truly cannot estimate, respond {\"low\": 0, \"high\": 0, \"currency\": \"USD\"} and the caller will treat it as unavailable.";
  const user = JSON.stringify({
    service: opts.service,
    params: opts.params,
    business: {
      name: opts.businessName,
      description: opts.businessDescription,
      pricing_profile: opts.pricingRawJson,
    },
  });
  const raw = await callClaude({ system, user, maxTokens: 200 });
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw) as { low?: unknown; high?: unknown; currency?: unknown };
    if (
      typeof parsed.low !== "number" ||
      typeof parsed.high !== "number" ||
      typeof parsed.currency !== "string" ||
      parsed.low < 0 || parsed.high < parsed.low
    ) return null;
    if (parsed.low === 0 && parsed.high === 0) return null; // Claude's "I don't know" sentinel
    return {
      low: parsed.low,
      high: parsed.high,
      currency: parsed.currency,
      confidence: "estimate",
      basis: "llm_estimate",
      disclaimer: LLM_DISCLAIMER,
    };
  } catch {
    return null;
  }
}

export async function handleGetQuote(
  input: z.infer<typeof getQuoteInput>
): Promise<{ content: Array<{ type: "text"; text: string }>; isError?: boolean }> {
  const row = getDb().prepare(`
    SELECT name, description, pricing_json_v2 FROM businesses WHERE slug = ?
  `).get(input.slug) as { name: string; description: string | null; pricing_json_v2: string | null } | undefined;

  if (!row) {
    return { isError: true, content: [{ type: "text", text: JSON.stringify({ error: "business_not_found", slug: input.slug }) }] };
  }
  let pricing: PricingJson = { ranges: [] };
  if (row.pricing_json_v2) {
    try { pricing = JSON.parse(row.pricing_json_v2) as PricingJson; } catch { /* fall through */ }
  }
  const det = deterministicQuote({ service: input.service, params: input.params ?? {} }, pricing);
  if (det) {
    return { content: [{ type: "text", text: JSON.stringify({ quote: det }) }] };
  }
  const llm = await llmQuoteFallback({
    service: input.service,
    params: input.params ?? {},
    businessName: row.name,
    businessDescription: row.description,
    pricingRawJson: row.pricing_json_v2,
  });
  if (llm) {
    return { content: [{ type: "text", text: JSON.stringify({ quote: llm }) }] };
  }
  return { content: [{ type: "text", text: JSON.stringify({ quote: null, reason: "llm_unavailable" }) }] };
}

export function registerGetQuote(
  server: McpServer,
  req?: Request,
  requestId?: string,
): void {
  server.tool(
    "get_quote",
    "Quote price for a service at a business. Deterministic lookup of pricing_json_v2.ranges[]; LLM fallback on miss, labelled 'estimate' with disclaimer.",
    getQuoteInput.shape,
    async (args) => {
      if (!req) return handleGetQuote(args);
      return withAgentRequestLog(
        {
          toolName: "get_quote",
          req,
          requestId,
          toolArgAgentId: null,
          businessSlug: args.slug,
        },
        () => handleGetQuote(args),
      );
    }
  );
}
