-- Migration 033 — Aggressive FAQ schema (Phase 1 of grey-hat AI optimization layer).
--
-- Each business gets a `faqs_json` array of {question, answer, intent} entries
-- generated by Claude at onboarding from the source profile. Renderers emit
-- these as a single FAQPage with N entries (vs. the legacy single-pair FAQPage
-- buildFaqJsonLd produced from {query, answerText}).
--
-- Why this matters: Sentry-grade competitors ship a single LocalBusiness +
-- generic FAQPage entry. AI crawlers preferentially cite Q&A formatted in the
-- exact phrasing users prompt with ("best <service> in <city>"). Pre-generating
-- 10-15 leading-question Q&As per business compounds citation surface area.
--
-- Provenance + anti-fabrication:
--   `faqs_source` records who/what generated the entry: 'claude' | 'manual' |
--   'imported'. The matching FaqSchema in server/src/schemas/business.ts caps
--   each answer at 280 chars (atomic facts only) and the generator's system
--   prompt explicitly forbids invented capabilities, hours, prices, certs,
--   or service areas. Provenance is preserved end-to-end so Legal can trace
--   any cited fact back to its source row.
--
-- Idempotent: ALTER TABLE ADD COLUMN is additive; CREATE INDEX IF NOT EXISTS
-- on the partial index. Safe to re-run.

ALTER TABLE businesses ADD COLUMN faqs_json TEXT;            -- JSON: [{question, answer, intent}]
ALTER TABLE businesses ADD COLUMN faqs_generated_at INTEGER; -- Unix epoch (ms) of last generation
ALTER TABLE businesses ADD COLUMN faqs_source TEXT;          -- 'claude' | 'manual' | 'imported'

-- Partial index on rows that have FAQs — used by the backfill cron to find
-- tenants needing first-time generation (faqs_json IS NULL) and to find
-- stale rows for re-generation (faqs_generated_at < threshold).
CREATE INDEX IF NOT EXISTS idx_biz_faqs_generated
  ON businesses(faqs_generated_at)
  WHERE faqs_json IS NOT NULL;
